import React from 'react';
import { Button } from 'react-bootstrap';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Card } from '../types';
import { FaFileDownload } from 'react-icons/fa';
import { useQuery } from '@tanstack/react-query';
import axios from 'axios';
import { useAuth0 } from '@auth0/auth0-react';
import { useNavigate } from 'react-router-dom';

// Étendre le type jsPDF pour inclure autotable
declare module 'jspdf' {
  interface jsPDF {
    autoTable: (options: any) => jsPDF;
  }
}

interface PdfExportProps {
  cards: Card[];
  collectionName?: string;
}

const PdfExport: React.FC<PdfExportProps> = ({ cards, collectionName = 'My Collection' }) => {
  const { getAccessTokenSilently, user } = useAuth0();
  const navigate = useNavigate();

  // Vérifier la souscription de l'utilisateur
  const { data: subscriptionData, isLoading } = useQuery({
    queryKey: ['subscription'],
    queryFn: async () => {
      const token = await getAccessTokenSilently();
      const response = await axios.get('http://localhost:3001/api/subscriptions/current', {
        headers: {
          'Authorization': `Bearer ${token}`,
          'x-user-id': user?.sub || 'anonymous-user'
        }
      });
      return response.data;
    },
    enabled: !!user
  });

  const generatePDF = () => {
    // Créer un nouveau document PDF
    const doc = new jsPDF();
    const now = new Date();
    const dateStr = `${now.toLocaleDateString()} ${now.toLocaleTimeString()}`;
    
    // Ajouter un titre
    doc.setFontSize(18);
    doc.text(`${collectionName} - MyCardCollection`, 14, 22);
    
    doc.setFontSize(11);
    doc.setTextColor(100);
    doc.text(`Generated on: ${dateStr}`, 14, 30);
    
    // Préparer les données pour le tableau
    const tableColumn = ["Name", "Category", "Price ($)", "Status", "Date", "Sold Price ($)", "Profit/Loss ($)"];
    const tableRows: any[] = [];

    // Formater la date pour l'affichage
    const formatDate = (dateString?: string) => {
      if (!dateString) return 'N/A';
      const date = new Date(dateString);
      return date.toLocaleDateString();
    };

    // Calculer les totaux
    let totalInvestment = 0;
    let totalSold = 0;
    let totalProfit = 0;

    // Ajouter chaque carte comme une ligne dans le tableau
    cards.forEach(card => {
      const profit = card.soldPrice && card.status === 'sold' 
        ? card.soldPrice - card.price
        : 0;
      
      // Collecter les statistiques
      if (card.status === 'bought') {
        totalInvestment += card.price;
      } else if (card.status === 'sold') {
        totalInvestment += card.price;
        totalSold += card.soldPrice || 0;
        totalProfit += profit;
      }

      // Formatter les données
      const dateToShow = card.status === 'bought' 
        ? formatDate(card.boughtDate) 
        : formatDate(card.soldDate);

      const tableRow = [
        card.name,
        card.category || 'N/A',
        card.price.toFixed(2),
        card.status === 'bought' ? 'In Collection' : 'Sold',
        dateToShow,
        card.soldPrice ? card.soldPrice.toFixed(2) : '-',
        card.status === 'sold' ? profit.toFixed(2) : '-'
      ];
      tableRows.push(tableRow);
    });

    // Ajouter le tableau au document PDF
    autoTable(doc, {
      head: [tableColumn],
      body: tableRows,
      startY: 40,
      styles: { fontSize: 10, cellPadding: 3 },
      headStyles: { fillColor: [41, 128, 185], textColor: 255 },
      alternateRowStyles: { fillColor: [245, 245, 245] },
      margin: { top: 40 }
    });

    // Ajouter les statistiques en fin de document
    const finalY = (doc as any).lastAutoTable.finalY || 40;
    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.text('Collection Summary:', 14, finalY + 10);
    
    doc.setFontSize(10);
    doc.text(`Total Cards: ${cards.length}`, 14, finalY + 20);
    doc.text(`Cards in Collection: ${cards.filter(c => c.status === 'bought').length}`, 14, finalY + 25);
    doc.text(`Cards Sold: ${cards.filter(c => c.status === 'sold').length}`, 14, finalY + 30);
    doc.text(`Total Investment: $${totalInvestment.toFixed(2)}`, 14, finalY + 35);
    doc.text(`Total Sales: $${totalSold.toFixed(2)}`, 14, finalY + 40);
    doc.text(`Total Profit/Loss: $${totalProfit.toFixed(2)}`, 14, finalY + 45);

    // Ajouter la signature en bas de page
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text('Generated by MyCardCollection', 14, 280);

    // Télécharger le PDF
    doc.save(`${collectionName.replace(/\s+/g, '_')}_cards_${now.toISOString().split('T')[0]}.pdf`);
  };

  const handleExportClick = () => {
    if (subscriptionData?.subscription?.name !== 'Premium') {
      navigate('/subscription');
      return;
    }
    generatePDF();
  };

  // Si l'utilisateur n'a pas de souscription premium, désactiver le bouton
  const isPremium = subscriptionData?.subscription?.name === 'Premium';
  const isDisabled = isLoading || !isPremium;

  return (
    <Button 
      variant="outline-success" 
      className="me-2" 
      onClick={handleExportClick}
      disabled={isDisabled}
      title={!isPremium ? "Export PDF disponible uniquement pour les utilisateurs Premium" : ""}
    >
      <FaFileDownload className="me-1" /> Export to PDF
    </Button>
  );
};

export default PdfExport; 